### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by Jiar** [zzhoujay/V2EX#1]
06-15 14:45:51.930 2693-2711/zhou.v2ex W/EGL_emulation: eglSurfaceAttrib not implemented
06-15 14:45:51.931 2693-2711/zhou.v2ex W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa30e9040, error=EGL_SUCCESS
06-15 14:45:52.516 2693-4118/zhou.v2ex D/requestString: success
06-15 14:45:53.175 2693-2693/zhou.v2ex D/login: failure

**Comment by Jiar** [comment]
将

```
response.code() == 302
```

改成

```
response.code() == 302 || response.code() == 200
```

即可。

**Comment by zzhoujay** [comment]
谢谢！已经修改了
